apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: machine-task  # Added namespace
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432  
          env:
            - name: POSTGRES_DB
              value: "microservice_one_user"  # Database name
            - name: POSTGRES_USER
              value: "postgres"  # Database user
            - name: POSTGRES_PASSWORD
              value: "2585"  # Database password
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: machine-task  # Added namespace
  labels:
    app: postgres-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-db
