apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: machine-task  # Added namespace
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379  # Redis default port
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "125m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: machine-task  # Added namespace
  labels:
    app: redis
spec:
  type: ClusterIP  # Redis is typically accessed internally within the cluster
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
